pipeline {
    agent {
        docker {
            image 'docker:27.3.1' 
            args '--privileged -v /certs:/certs -e DOCKER_TLS_CERTDIR=/certs --host tcp://dind:2376'

        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest --junit-xml test-reports/results.xml sources/test_calc.py'
            }
        }
        stage('Deploy') {
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
        }
    }
}

